service: notar

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  getKey:
    handler: keys/get.main
    events:
      - http:
          cors: true
          path: /keys/
          method: get
          authorizer: aws_iam
